<a href="https://colab.research.google.com/github/Team2009/Team2009/blob/main/signate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# int型変換

In [ ]:
import joblib
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from google.colab import files

# 例としてデータロードとモデル訓練を行います
uploaded = files.upload()

# TSVファイルをロード
df = pd.read_csv('train_8.tsv', sep='\t', dtype=str)

# 変換できない値を格納する辞書
non_convertible_values = {}

# 各カラムをint型に変換
for column in df.columns:
    non_convertible_values[column] = []
    for index, value in df[column].items():
        try:
            # 値を整数に変換
            int_value = int(value)
        except ValueError:
            # 変換できない場合はリストに追加
            non_convertible_values[column].append(value)

# 変換できない値を出力
for column, values in non_convertible_values.items():
    if values:
        print(f"Column '{column}' has non-convertible values: {values}")

# 変換可能な部分をint型に変換（エラーが出たカラムを無視する）
for column in df.columns:
    df[column] = pd.to_numeric(df[column], errors='coerce')

# NaNが残った部分は変換できなかった値を示す
print("Transformed DataFrame:")
print(df)

# 必要に応じて、変換後のデータを新しいTSVファイルに保存
# df.to_csv('converted_file.tsv', sep='\t', index=False)

Saving train_8.tsv to train_8 (1).tsv
Column 'class' has non-convertible values: ['unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'vgood', 'unacc', 'unacc', 'unacc', 'good', 'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'acc', 'vgood', 'unacc', 'unacc', 'unacc', 'acc', 'good', 'acc', 'unacc', 'acc', 'vgood', 'unacc', 'acc', 'acc', 'good', 'acc', 'vgood', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'vgood', 'vgood', 'vgood', 'unacc', 'unacc', 'acc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'vgood', 'acc', 'acc', 'acc', 'unacc', 'unacc', 'acc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'vgood', 'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'acc', 'unacc', 'acc', 'unacc', '

# 文字列置換_数字も変えちゃうNG

In [ ]:
import joblib
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from google.colab import files

# 例としてデータロードとモデル訓練を行います
uploaded = files.upload()

# TSVファイルをロード
df = pd.read_csv('train.tsv', sep='\t', dtype=str)

# 変換ルールを定義
conversion_map = {
    'vhigh': 1,
    'high': 2,
    'med': 3,
    'low': 4,
    'small':5,
    'big':6,


}

# 3カラム目（通常はインデックス2）を条件に基づいて変換
column_index = 2  # ここを変えれば別のカラムを指定できます

def convert_value(value):
    # 変換マップで指定されている値ならマップの値を、それ以外なら5を返す
    return conversion_map.get(value, 7)

# 3カラム目以降の全てを変換する
for column in df.columns[2:]:
    df[column] = df[column].apply(convert_value)

# 変換後のデータフレームを表示
print(df)

# 必要に応じて、新しいTSVファイルに保存
df.to_csv('int_train.tsv', sep='\t', index=False)
files.download('int_train.tsv')

Saving train.tsv to train.tsv
       id  class  buying  maint  doors  persons  lug_boot  safety
0       0  unacc       4      3      7        7         5       4
1       3    acc       4      2      7        7         5       3
2       7  unacc       1      2      7        7         5       3
3      11    acc       2      2      7        7         6       3
4      12  unacc       2      2      7        7         3       2
..    ...    ...     ...    ...    ...      ...       ...     ...
859  1721    acc       2      2      7        7         3       3
860  1722  unacc       2      2      7        7         5       3
861  1724  unacc       2      4      7        7         3       4
862  1725  unacc       4      4      7        7         5       3
863  1726  unacc       4      1      7        7         5       4

[864 rows x 8 columns]


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# 文字列変換r2

In [ ]:
import joblib
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from google.colab import files

# 例としてデータロードとモデル訓練を行います
uploaded = files.upload()

# TSVファイルをロード
df = pd.read_csv('train.tsv', sep='\t', dtype=str)

# 変換ルールを定義
conversion_map = {
    'vhigh': 1,
    'high': 2,
    'med': 3,
    'low': 4,
    'small':5,
    'big':6,
}

# 3カラム目（通常はインデックス2）を条件に基づいて変換
column_index = 2  # ここを変えれば別のカラムを指定できます

def convert_value(value):
    try:
        # もともと数字の場合はそのまま返す
        return int(value)
    except ValueError:
        # 変換マップで指定されている値ならマップの値を、それ以外なら5を返す
        return conversion_map.get(value, 7)

# 3カラム目以降の全てを変換する
for column in df.columns[2:]:
    df[column] = df[column].apply(convert_value)

# 変換後のデータフレームを表示
print(df)

# 必要に応じて、新しいTSVファイルに保存
df.to_csv('int_train.tsv', sep='\t', index=False)
files.download('int_train.tsv')

Saving train.tsv to train (2).tsv
       id  class  buying  maint  doors  persons  lug_boot  safety
0       0  unacc       4      3      3        2         5       4
1       3    acc       4      2      3        7         5       3
2       7  unacc       1      2      7        2         5       3
3      11    acc       2      2      3        7         6       3
4      12  unacc       2      2      3        2         3       2
..    ...    ...     ...    ...    ...      ...       ...     ...
859  1721    acc       2      2      7        7         3       3
860  1722  unacc       2      2      7        4         5       3
861  1724  unacc       2      4      3        7         3       4
862  1725  unacc       4      4      7        2         5       3
863  1726  unacc       4      1      4        7         5       4

[864 rows x 8 columns]


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# トレーニングセット分割

In [ ]:
uploaded = files.upload()

# Assuming the file name is 'train.tsv'
df = pd.read_csv('int_train.tsv', sep='\t')

# データをシャッフルして分割
from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(df, test_size=0.2, random_state=42)

# データの確認
print("Training set size:", len(train_df))
print("Validation set size:", len(val_df))

# 分割したデータをTSVファイルとして保存:
train_df.to_csv('int_train8.tsv', sep='\t', index=False)
val_df.to_csv('int_train2.tsv', sep='\t', index=False)

# データの保存
files.download('int_train8.tsv')
files.download('int_train2.tsv')

Saving int_train.tsv to int_train (2).tsv
Training set size: 691
Validation set size: 173


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# 決定木モデル作成

In [ ]:
import pandas as pd
import joblib
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from google.colab import files

# 訓練用データを読み込む
uploaded = files.upload()
train_file = 'int_train8.tsv'
train_data = pd.read_csv(train_file, sep='\t', header=0)

# 説明変数と目的変数を分ける
X_train = train_data.iloc[1:, 2:8]  # 3,4,5,6,7,8カラム目が説明変数
y_train = train_data.iloc[1:, 1]    # 2カラム目が目的変数

# 各カラムのデータ型を出力
print("=== Initial Data Types (train8) ===")
print(X_train)
print("------")
print(X_train.dtypes)

# モデルを作成し訓練する
model = DecisionTreeClassifier(random_state=0)
model.fit(X_train, y_train)

# モデルを保存する
model_filename = 'int_decision_tree_model.joblib'
joblib.dump(model, model_filename)
# データの保存
files.download('int_decision_tree_model.joblib')

### 以下デバッグ用
# 評価用データを読み込む
#test_file = 'int_train2.tsv'
#test_data = pd.read_csv(test_file, sep='\t', header=0)

# 2行目以降の3,4,5,6,7,8カラム目を説明変数として取得（ヘッダを含まない）
#test_data = test_data.iloc[:, 2:8]  # 2行目以降を取得

# 各カラムのデータ型を出力
#print("=== Initial Data Types (train2) ===")
#print(test_data)
#print("------")
#print(test_data.dtypes)

# データが数値型であるか確認し、必要に応じて変換する
#test = test.apply(pd.to_numeric, errors='coerce')

# 新しいデータで目的変数を予測する
#predictions = model.predict(test_data)

# 予測結果を出力する
#output = pd.DataFrame(predictions, columns=['Predicted'])
#output.to_csv('predictions.csv', index=False)
# データの保存
#files.download('predictions.csv')


Saving int_train2.tsv to int_train2 (4).tsv
Saving int_train8.tsv to int_train8 (4).tsv
=== Initial Data Types (train8) ===
     buying  maint  doors  persons  lug_boot  safety
1         3      2      3        4         3       2
2         2      2      7        7         5       4
3         2      3      3        2         6       4
4         2      4      7        4         5       4
5         4      2      2        2         3       3
..      ...    ...    ...      ...       ...     ...
686       2      2      2        4         5       2
687       2      4      2        7         3       3
688       2      2      7        4         5       3
689       2      2      3        4         5       2
690       1      1      3        4         5       2

[690 rows x 6 columns]
------
buying      int64
maint       int64
doors       int64
persons     int64
lug_boot    int64
safety      int64
dtype: object


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# 20241121_初期決定木モデル作成コード

In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from google.colab import files

# ローカルファイルをアップロード
uploaded = files.upload()

# ファイルの読み込み
train_file = 'train_8.tsv'
val_file = 'train_2.tsv'

# データの読み込み
train_data = pd.read_csv(train_file, sep='\t', header=None)
val_data = pd.read_csv(val_file, sep='\t', header=None)

# 1行目が不要なら削除（場合によって削除が必要）
train_data = train_data.drop(index=0).reset_index(drop=True)
val_data = val_data.drop(index=0).reset_index(drop=True)

# 説明変数と目的変数の分割
X_train = train_data.drop(columns=1)
y_train = train_data[1]

X_val = val_data.drop(columns=1)
y_val = val_data[1]

# Categorical feature encoding
X_train = pd.get_dummies(X_train)
X_val = pd.get_dummies(X_val)

# 対応する列を合わせる（片方にしかない列をカバー）
X_train, X_val = X_train.align(X_val, join='left', axis=1, fill_value=0)

# 決定木モデルのインスタンス作成と訓練
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)

# 検証データでの予測と評価
predictions = clf.predict(X_val)
accuracy = accuracy_score(y_val, predictions)
print(f"Accuracy: {accuracy * 100:.2f}%")

# 必要に応じて、分類レポートや混同行列の出力も可能
from sklearn.metrics import classification_report, confusion_matrix

print("\nClassification Report:")
print(classification_report(y_val, predictions))

print("\nConfusion Matrix:")
print(confusion_matrix(y_val, predictions))

# 20241122のデータのモデル評価

In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from google.colab import files

# ローカルファイルをアップロード
uploaded = files.upload()

# ファイルの読み込み
train_file = 'int_train8.tsv'
val_file = 'int_train2.tsv'

# データの読み込み
train_data = pd.read_csv(train_file, sep='\t', header=None)
val_data = pd.read_csv(val_file, sep='\t', header=None)

# 1行目が不要なら削除（場合によって削除が必要）
train_data = train_data.drop(index=0).reset_index(drop=True)
val_data = val_data.drop(index=0).reset_index(drop=True)

# 説明変数と目的変数の分割
X_train = train_data.drop(columns=1)
y_train = train_data[1]

X_val = val_data.drop(columns=1)
y_val = val_data[1]

# Categorical feature encoding
X_train = pd.get_dummies(X_train)
X_val = pd.get_dummies(X_val)

# 対応する列を合わせる（片方にしかない列をカバー）
X_train, X_val = X_train.align(X_val, join='left', axis=1, fill_value=0)

# 決定木モデルのインスタンス作成と訓練
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)

# 検証データでの予測と評価
predictions = clf.predict(X_val)
accuracy = accuracy_score(y_val, predictions)
print(f"Accuracy: {accuracy * 100:.2f}%")

# 必要に応じて、分類レポートや混同行列の出力も可能
from sklearn.metrics import classification_report, confusion_matrix

print("\nClassification Report:")
print(classification_report(y_val, predictions))

print("\nConfusion Matrix:")
print(confusion_matrix(y_val, predictions))

Saving int_train2.tsv to int_train2 (8).tsv
Saving int_train8.tsv to int_train8 (8).tsv
Accuracy: 94.80%

Classification Report:
              precision    recall  f1-score   support

         acc       0.89      0.93      0.91        43
        good       0.75      0.43      0.55         7
       unacc       0.98      0.99      0.99       119
       vgood       0.75      0.75      0.75         4

    accuracy                           0.95       173
   macro avg       0.84      0.78      0.80       173
weighted avg       0.95      0.95      0.94       173


Confusion Matrix:
[[ 40   1   2   0]
 [  3   3   0   1]
 [  1   0 118   0]
 [  1   0   0   3]]


# 文字列変換r2_test.tsv用

In [ ]:
import joblib
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from google.colab import files

# 例としてデータロードとモデル訓練を行います
uploaded = files.upload()

# TSVファイルをロード
df = pd.read_csv('test.tsv', sep='\t', dtype=str)

# 変換ルールを定義
conversion_map = {
    'vhigh': 1,
    'high': 2,
    'med': 3,
    'low': 4,
    'small':5,
    'big':6,
}

# 3カラム目（通常はインデックス2）を条件に基づいて変換
column_index = 2  # ここを変えれば別のカラムを指定できます

def convert_value(value):
    try:
        # もともと数字の場合はそのまま返す
        return int(value)
    except ValueError:
        # 変換マップで指定されている値ならマップの値を、それ以外なら5を返す
        return conversion_map.get(value, 7)

# 2カラム目以降の全てを変換する
for column in df.columns[1:]:
    df[column] = df[column].apply(convert_value)

# 変換後のデータフレームを表示
print(df)

# 必要に応じて、新しいTSVファイルに保存
df.to_csv('int_test.tsv', sep='\t', index=False)
files.download('int_test.tsv')

Saving test.tsv to test (3).tsv
       id  buying  maint  doors  persons  lug_boot  safety
0       1       2      1      2        7         6       4
1       2       1      1      7        4         5       2
2       4       3      2      2        2         5       4
3       5       3      3      4        4         6       3
4       6       2      2      2        4         3       4
..    ...     ...    ...    ...      ...       ...     ...
859  1718       4      4      3        2         6       2
860  1719       3      4      7        2         6       3
861  1720       1      1      3        2         6       3
862  1723       2      1      4        4         5       4
863  1727       4      2      3        2         5       2

[864 rows x 7 columns]


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# 実践してみる

In [ ]:
import pandas as pd
import joblib
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from google.colab import files

# 保存されたモデルを読み込む
uploaded = files.upload()
model_filename = 'int_decision_tree_model.joblib'
model = joblib.load(model_filename)

# 評価用データを読み込む
test_file = 'int_test.tsv'
test_data = pd.read_csv(test_file, sep='\t', header=0)
### デバッグ
# print("---test_data---")
# print(test_data)

# 2行目から説明変数を取得（2,3,4,5,6,7カラム目を使用）
X_test = test_data.iloc[0:, 1:7]  # 2行目以降の2-7カラム目を使用

### デバッグ
# print("---X_test---")
# print(X_test)
# データが数値型であるか確認、必要に応じて変換する
# X_test = X_test.apply(pd.to_numeric, errors='coerce')

# 予測を行う
predictions = model.predict(X_test)

# 出力結果のDataFrameを作成
output = pd.DataFrame({
    'Original_Value': test_data.iloc[0:, 0].values,  # 1カラム目のデータ
    'Predicted': predictions  # モデルの予測値
})

# CSVファイルに出力
# CSVに保存（ヘッダー無し）
result_filename = 'int_tree_result.csv'
output.to_csv(result_filename, index=False, header=False)
print(f"Predictions saved to {result_filename}")
files.download('int_tree_result.csv')

Saving int_decision_tree_model.joblib to int_decision_tree_model (12).joblib
Saving int_test.tsv to int_test (10).tsv
Predictions saved to int_tree_result.csv


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# ----------以下別モデル----------

# ランダムフォレスト対応

In [33]:
import pandas as pd
import joblib
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from google.colab import files
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import make_scorer, f1_score

# TSVファイルからデータを読み込む
# 保存されたモデルを読み込む
uploaded = files.upload()

# 訓練用データの読み込み
data = pd.read_csv('int_train.tsv', sep='\t')

# 特徴量とターゲットを分ける
feature_columns = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety']
X = data[feature_columns]
y = data['class']

# 訓練データとテストデータに分割
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# ランダムフォレストモデルのインスタンス化
rf = RandomForestClassifier(random_state=42)

# グリッドサーチで調整するハイパーパラメータの範囲を定義
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt', 'log2']
}

# スコアとしてF1スコアを使用
scorer = make_scorer(f1_score, average='weighted')  # 不均衡データでも全体を考慮

# グリッドサーチの設定
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5, scoring=scorer, n_jobs=-1, verbose=2)

# グリッドサーチの実行
grid_search.fit(X_train, y_train)

# ベストパラメータとベストスコアを取得
best_params = grid_search.best_params_
best_score = grid_search.best_score_
print("Best Parameters:", best_params)
print("Best F1 Score:", best_score)

# ベストモデルでテストデータを評価
best_model = grid_search.best_estimator_
test_score = f1_score(y_test, best_model.predict(X_test), average='weighted')
print("Test F1 Score:", test_score)

Saving int_train.tsv to int_train (2).tsv
Fitting 5 folds for each of 324 candidates, totalling 1620 fits


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:540: FitFailedWarning: 
540 fits failed out of a total of 1620.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
540 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/uti

InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.